version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.14.0
  aws-ecs: circleci/aws-ecs@1.1.0
workflows:
  nginx-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          context: .
          create-repo: true
          dockerfile: Dockerfile_Nginx
          no-output-timeout: 20m
          path: ./
          profile-name: yoshin04/nginx
          region: ${AWS_DEFAULT_REGION}
          repo: nginx
          skip-when-tags-exist: false
          tag: 'latest'
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image:
          aws-region: ${AWS_DEFAULT_REGION}
          family: "laravel-fagate-task"
          service-name: "laravel-fargate-service"
          cluster-name: "laravel-fagate"
          container-image-name-updates: "container=app,image-and-tag=${AWS_ECR_ACCOUNT_URL}/nginx:${CIRCLE_SHA1}"
  #         # filters:
  #         #   branches:
  #         #     only:
  #         #       - master
  laravelapp-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_DEFAULT_REGION}
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build_and_push_image
          aws-region: ${AWS_DEFAULT_REGION}
          family: "laravel-fagate-task"
          service-name: "laravel-fargate-service"
          cluster-name: "laravel-fagate"
          container-image-name-updates: "container=app,image-and-tag=${AWS_ECR_ACCOUNT_URL}/laravelapp:${CIRCLE_SHA1}"
          # filters:
          #   branches:
          #     only:
          #       - master


