version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
  aws-ecs: circleci/aws-ecs@1.1.0
jobs:
  build:
    - run:
        name: Docker-compose
        commmand: |
        curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
        chmod +x ~/docker-compose
        sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
        name: docker-compose start-up
        command: |
        set -x
        docker-compose up -d --build
        dokcer-compose down
workflows:
  laravelapp-deploy:
    jobs:
      - build:
      - aws-ecr/build_and_push_image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_DEFAULT_REGION}
          tag: "latest"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build_and_push_image
          aws-region: ${AWS_DEFAULT_REGION}
          family: "laravel-fagate-task"
          service-name: "laravel-fargate-service"
          cluster-name: "laravel-fagate"
          container-image-name-updates: "container=app,tag=latest"
          # filters:
          #   branches:
          #     only:
          #       - master


