version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.14.0
  aws-ecs: circleci/aws-ecs@1.1.0
build:
  docker:
    - image: circleci/php:7.3-node-browsers
  steps:
    - run:
      name: deploy
      ommand: |
        ssh -o StrictHostKeyChecking=no -t webapp@${HOST_NAME} "cd laravel-ci && \
        git pull origin master && \
        composer install -n --no-dev --prefer-dist && \
        npm ci && \
        npm run prod && \
        php artisan migrate --force && \
        php artisan config:cache"
workflows:
  laravelapp-deploy:
    jobs:
      - build
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          dockerfile: Dockerfile
          path: .
          region: AWS_REGION
          repo: laravelapp
          tag: 'latest'
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: "laravel-fagate-task"
          service-name: "laravel-fargate-service"
          cluster-name: "laravel-fagate"
          container-image-name-updates: "container=app,image-and-tag=${AWS_ECR_ACCOUNT_URL}/laravelapp:latest"
          # filters:
          #   branches:
          #     only:
          #       - master

  nginx-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          dockerfile: Dockerfile_Nginx
          path: .
          region: AWS_REGION
          repo: nginx
          tag: 'latest'
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: "laravel-fagate-task"
          service-name: "laravel-fargate-service"
          cluster-name: "laravel-fagate"
          container-image-name-updates: "container=nginx,image-and-tag=${AWS_ECR_ACCOUNT_URL}/nginx:latest"
  #         # filters:
  #         #   branches:
  #         #     only:
  #         #       - master
 

