version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@0.0.2
  aws-ecs: circleci/aws-ecs@0.0.10
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_DEFAULT_REGION}
          tag: "latest"
          path: ./
          dockerfile: Dockerfile
          requires:
            - build
          # filters:
          #   branches:
          #     only:
          #       - master
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build_and_push_image
          aws-region: ${AWS_DEFAULT_REGION}
          family: "laravel-fagate-task"
          service-name: "laravel-fargate-service"
          cluster-name: "laravel-fagate"
          container-image-name-updates: "container=app,tag=latest"
          # filters:
          #   branches:
          #     only:
          #       - master

