version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
  aws-ecs: circleci/aws-ecs@1.1.0
workflows:
  nginx-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
        account-url: "721817511144.dkr.ecr.ap-northeast-1.amazonaws.com"
        dockerfile: ./Dockerfile_Nginx
        repo: "nginx"
        region: ${AWS_DEFAULT_REGION}
        tag: "latest"
      - aws-ecs/deploy-service-update: 
          requires:
            - aws-ecr/build_and_push_image
          aws-region: ${AWS_DEFAULT_REGION}
          family: "laravel-fagate-task"
          service-name: "laravel-fargate-service"
          cluster-name: "laravel-fagate"
          container-image-name-updates: "container=nginx,tag=latest"
  laravelapp-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_DEFAULT_REGION}
          tag: "latest"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build_and_push_image
          aws-region: ${AWS_DEFAULT_REGION}
          family: "laravel-fagate-task"
          service-name: "laravel-fargate-service"
          cluster-name: "laravel-fagate"
          container-image-name-updates: "container=app,tag=latest"
          # filters:
          #   branches:
          #     only:
          #       - master


